import type { SpecialDay } from './types/SpecialDay'
import { RunicDayId } from './const/SpecialDayId'
import { getDateString } from './helpers/getDateString'

export function getRunicDays(year: number = new Date().getFullYear()): SpecialDay[] {
  return [
    {
      date: getDateString(1, 1, year),
      name: 'Nyttårsdag, åttendedagen',
      type: 'runic',
      id: RunicDayId.EighthDay,
    },
    {
      date: getDateString(6, 1, year),
      name: 'Helligtrekongersdag, trettendedagen',
      type: 'runic',
      id: RunicDayId.Epiphany,
    },
    {
      date: getDateString(7, 1, year),
      name: 'Eldbjørgdag, ildbergingsdag, St. Knut',
      type: 'runic',
      id: RunicDayId.EldbjorgDay,
    },
    {
      date: getDateString(11, 1, year),
      name: 'Brettemesse, brokkismesse, brykkesmesse',
      type: 'runic',
      id: RunicDayId.Brettemesse,
    },
    {
      date: getDateString(12, 1, year),
      name: 'Midtvinterdag, hökunótt',
      type: 'runic',
      id: RunicDayId.MidwinterDay,
    },
    {
      date: getDateString(13, 1, year),
      name: 'Tjuendedagen, Knutsdag, avfaredag, gamle nyttårsdag',
      type: 'runic',
      id: RunicDayId.TwentiethDay,
    },
    {
      date: getDateString(14, 1, year),
      name: 'Midtvinterdagen (hedensk jul)',
      type: 'runic',
      id: RunicDayId.MidwinterDayPagan,
    },
    {
      date: getDateString(17, 1, year),
      name: 'Antonsmesse',
      type: 'runic',
      id: RunicDayId.AntonMesse,
    },
    {
      date: getDateString(20, 1, year),
      name: 'Brødremesse',
      type: 'runic',
      id: RunicDayId.BreadMesse,
    },
    {
      date: getDateString(25, 1, year),
      name: 'Pålsmesse, Pål med bogen, Pål skytter',
      type: 'runic',
      id: RunicDayId.PaulMesse,
    },
    {
      date: getDateString(2, 2, year),
      name: 'Kyndelsmesse, kindermesse, kjærmesse, lysenes messe, missa candelarum',
      type: 'runic',
      id: RunicDayId.Candlemas,
    },
    {
      date: getDateString(3, 2, year),
      name: 'Blåsmesse, Blåsius',
      type: 'runic',
      id: RunicDayId.BlasiusMesse,
    },
    {
      date: getDateString(5, 2, year),
      name: 'Ågotsmesse, musedagen',
      type: 'runic',
      id: RunicDayId.AgotMesse,
    },
    {
      date: getDateString(22, 2, year),
      name: 'Peters stol, Per varmestein, Per heitstein',
      type: 'runic',
      id: RunicDayId.PetersChair,
    },
    {
      date: getDateString(24, 2, year),
      name: 'Mattismesse vår, Mattis',
      type: 'runic',
      id: RunicDayId.MatthewMesseSpring,
    },
    {
      date: getDateString(9, 3, year),
      name: 'De førti riddere',
      type: 'runic',
      id: RunicDayId.FortyKnights,
    },
    {
      date: getDateString(12, 3, year),
      name: 'Gregormesse, Gregoriusdagen, Gregusmesse, Groårsmesse',
      type: 'runic',
      id: RunicDayId.GregoryMesse,
    },
    {
      date: getDateString(17, 3, year),
      name: 'Gjertrudsmesse, Gjertrudsdagen',
      type: 'runic',
      id: RunicDayId.GertrudeMesse,
    },
    {
      date: getDateString(18, 3, year),
      name: 'Petrus martyr, Per pekk i vatn',
      type: 'runic',
      id: RunicDayId.PetrusMartyr,
    },
    {
      date: getDateString(21, 3, year),
      name: 'Bendiksmesse, Bendik/Bent prøvesvin, (vårjevndøgn, jamvår)',
      type: 'runic',
      id: RunicDayId.BenedictMesse,
    },
    {
      date: getDateString(25, 3, year),
      name: 'Maria bebudelsesdag, vårfrumesse, Marimesse, vårmesse',
      type: 'runic',
      id: RunicDayId.Annunciation,
    },
    {
      date: getDateString(14, 4, year),
      name: 'Sommermål, sommerdag, sommernatt',
      type: 'runic',
      id: RunicDayId.SummerSolstice,
    },
    {
      date: getDateString(16, 4, year),
      name: 'Magnusmesse, tredjedag sommer',
      type: 'runic',
      id: RunicDayId.MagnusMesse,
    },
    {
      date: getDateString(23, 4, year),
      name: 'Jørgensdag',
      type: 'runic',
      id: RunicDayId.GeorgesDay,
    },
    {
      date: getDateString(25, 4, year),
      name: 'Markusmesse, Markusdagen, store gangdag',
      type: 'runic',
      id: RunicDayId.MarkMesse,
    },
    {
      date: getDateString(1, 5, year),
      name: 'Gauksmesse, lille gangdag',
      type: 'runic',
      id: RunicDayId.GauksMesse,
    },
    {
      date: getDateString(3, 5, year),
      name: 'Korsmesse vår',
      type: 'runic',
      id: RunicDayId.CrossMesseSpring,
    },
    {
      date: getDateString(15, 5, year),
      name: 'Hallvardsmesse, Hallvardsvaka, hallsok',
      type: 'runic',
      id: RunicDayId.HallvardMesse,
    },
    {
      date: getDateString(18, 5, year),
      name: 'Eriksmesse',
      type: 'runic',
      id: RunicDayId.ErikMesse,
    },
    {
      date: getDateString(22, 5, year),
      name: 'Bjørnevåk',
      type: 'runic',
      id: RunicDayId.BearWake,
    },
    {
      date: getDateString(25, 5, year),
      name: 'Urbanus',
      type: 'runic',
      id: RunicDayId.Urbanus,
    },
    {
      date: getDateString(3, 6, year),
      name: 'Rasmusdagen, skoklefallsdagen',
      type: 'runic',
      id: RunicDayId.RasmusDay,
    },
    {
      date: getDateString(8, 6, year),
      name: 'Medardus og Gilardus',
      type: 'runic',
      id: RunicDayId.MedardusAndGilardus,
    },
    {
      date: getDateString(9, 6, year),
      name: 'Kolumbamesse, Kolbjørn med laksen',
      type: 'runic',
      id: RunicDayId.ColumbaMesse,
    },
    {
      date: getDateString(17, 6, year),
      name: 'Botolfsmesse, botsok',
      type: 'runic',
      id: RunicDayId.BotolfMesse,
    },
    {
      date: getDateString(21, 6, year),
      name: 'Sommersolverv',
      type: 'runic',
      id: RunicDayId.SummerSolsticeRunic,
    },
    {
      date: getDateString(22, 6, year),
      name: 'De ti tusen riddere, de ti tusen martyrer',
      type: 'runic',
      id: RunicDayId.TenThousandKnights,
    },
    {
      date: getDateString(24, 6, year),
      name: 'Sankthans, Jonsmesse, Jonsok',
      type: 'runic',
      id: RunicDayId.SankthansRunic,
    },
    {
      date: getDateString(29, 6, year),
      name: 'Petersmesse, Persok, Peter med gullnøkkelen',
      type: 'runic',
      id: RunicDayId.PeterMesse,
    },
    {
      date: getDateString(2, 7, year),
      name: 'Syftesok',
      type: 'runic',
      id: RunicDayId.SyfteSok,
    },
    {
      date: getDateString(8, 7, year),
      name: 'Tredjevaka, Kjell fut, Kjell sviebygg, Seljemannamesse, Sunniva Virginis',
      type: 'runic',
      id: RunicDayId.ThirdWake,
    },
    {
      date: getDateString(10, 7, year),
      name: 'Knutsmesse, knutsok, Knut med ljåen, Kong Knut',
      type: 'runic',
      id: RunicDayId.KnutMesse,
    },
    {
      date: getDateString(12, 7, year),
      name: 'Kari med riva',
      type: 'runic',
      id: RunicDayId.KariWithRake,
    },
    {
      date: getDateString(14, 7, year),
      name: 'Midtsommerdag',
      type: 'runic',
      id: RunicDayId.MidsummerDay,
    },
    {
      date: getDateString(20, 7, year),
      name: 'Marit Vassause, Margretemesse, Mari(t)messe',
      type: 'runic',
      id: RunicDayId.MargaretMesse,
    },
    {
      date: getDateString(22, 7, year),
      name: 'Mari stol, magdalidagen, magdalimesse',
      type: 'runic',
      id: RunicDayId.MarysChair,
    },
    {
      date: getDateString(25, 7, year),
      name: 'Jakobsmesse, Jakob våthatt',
      type: 'runic',
      id: RunicDayId.JamesMesse,
    },
    {
      date: getDateString(29, 7, year),
      name: 'Olsok, Olafsvaka',
      type: 'runic',
      id: RunicDayId.OlsokRunic,
    },
    {
      date: getDateString(1, 8, year),
      name: 'Peters lenker, Peder vindfells dag, Per vinkel',
      type: 'runic',
      id: RunicDayId.PetersChains,
    },
    {
      date: getDateString(3, 8, year),
      name: 'Vesle olsok, Olsok siare, Translatio Olavi',
      type: 'runic',
      id: RunicDayId.LittleOlsok,
    },
    {
      date: getDateString(10, 8, year),
      name: 'Larsok, Lavransvaka',
      type: 'runic',
      id: RunicDayId.LarsSok,
    },
    {
      date: getDateString(15, 8, year),
      name: 'Marimesse førre, våre frue dyre, Marias himmelfart',
      type: 'runic',
      id: RunicDayId.MaryMesseFirst,
    },
    {
      date: getDateString(24, 8, year),
      name: 'Barsok, Bartholomeusmesse, bardonsok, Berdon bukkekniv, Bertel brytestrå',
      type: 'runic',
      id: RunicDayId.BarSok,
    },
    {
      date: getDateString(29, 8, year),
      name: 'Vergismesse, Johannes halshogg',
      type: 'runic',
      id: RunicDayId.VergisMesse,
    },
    {
      date: getDateString(1, 9, year),
      name: 'Eidismesse, Kvernknarren',
      type: 'runic',
      id: RunicDayId.EidMesse,
    },
    {
      date: getDateString(8, 9, year),
      name: 'Marimesse siare, vår frue siare, morsmesse',
      type: 'runic',
      id: RunicDayId.MaryMesseSecond,
    },
    {
      date: getDateString(14, 9, year),
      name: 'Korsmesse høst',
      type: 'runic',
      id: RunicDayId.CrossMesseAutumn,
    },
    {
      date: getDateString(21, 9, year),
      name: 'Mattismesse høst, Mattheusmesse, Mattisdag, (høstjevndøgn)',
      type: 'runic',
      id: RunicDayId.MatthewMesseAutumn,
    },
    {
      date: getDateString(29, 9, year),
      name: 'Mikkelsmesse, mikeli',
      type: 'runic',
      id: RunicDayId.MichaelMesse,
    },
    {
      date: getDateString(4, 10, year),
      name: 'St. Frans',
      type: 'runic',
      id: RunicDayId.StFrancis,
    },
    {
      date: getDateString(7, 10, year),
      name: 'Britemesse',
      type: 'runic',
      id: RunicDayId.BriteMesse,
    },
    {
      date: getDateString(9, 10, year),
      name: 'Dinesmesse, Deinets dag',
      type: 'runic',
      id: RunicDayId.DineMesse,
    },
    {
      date: getDateString(14, 10, year),
      name: 'Vinternettene, vinterdag, vinternatt',
      type: 'runic',
      id: RunicDayId.WinterNights,
    },
    {
      date: getDateString(18, 10, year),
      name: 'Lukasmesse, Lukas våtmann',
      type: 'runic',
      id: RunicDayId.LukeMesse,
    },
    {
      date: getDateString(21, 10, year),
      name: 'Ursula, 11 000 jomfruer',
      type: 'runic',
      id: RunicDayId.Ursula,
    },
    {
      date: getDateString(28, 10, year),
      name: 'Simonsmesse, Simon og Judas',
      type: 'runic',
      id: RunicDayId.SimonMesse,
    },
    {
      date: getDateString(1, 11, year),
      name: 'Allehelgensdag, helgemesse, aldermesse',
      type: 'runic',
      id: RunicDayId.AllSaintsDay,
    },
    {
      date: getDateString(2, 11, year),
      name: 'Alle sjelers dag',
      type: 'runic',
      id: RunicDayId.AllSoulsDay,
    },
    {
      date: getDateString(11, 11, year),
      name: 'Mortensmesse, Mortensdag',
      type: 'runic',
      id: RunicDayId.MortensMesseRunic,
    },
    {
      date: getDateString(21, 11, year),
      name: 'Marioffer (Presentatio Mariae)',
      type: 'runic',
      id: RunicDayId.MaryOffering,
    },
    {
      date: getDateString(23, 11, year),
      name: 'Klemetsmesse, båtsok, Klemet kirkebygger, Klemet saueskjærer',
      type: 'runic',
      id: RunicDayId.ClementMesse,
    },
    {
      date: getDateString(25, 11, year),
      name: 'Karimesse, Karenmesse, Kari med rokken',
      type: 'runic',
      id: RunicDayId.KariMesse,
    },
    {
      date: getDateString(30, 11, year),
      name: 'Andersmesse, Anders fisker',
      type: 'runic',
      id: RunicDayId.AndrewMesse,
    },
    {
      date: getDateString(4, 12, year),
      name: 'Barbromesse, Barbrodøgnet',
      type: 'runic',
      id: RunicDayId.BarbroMesse,
    },
    {
      date: getDateString(6, 12, year),
      name: 'Nilsmesse, Nikolausdagen',
      type: 'runic',
      id: RunicDayId.NilsMesse,
    },
    {
      date: getDateString(8, 12, year),
      name: 'Maria unnfangelsesdag, vår frue ventedør',
      type: 'runic',
      id: RunicDayId.MaryConception,
    },
    {
      date: getDateString(9, 12, year),
      name: 'Anna matris Mariae, Anna røytrauv, (Anna) pissihose, Annadagen',
      type: 'runic',
      id: RunicDayId.AnnaDay,
    },
    {
      date: getDateString(13, 12, year),
      name: 'Lussimesse, Lussinatt, Luciadagen',
      type: 'runic',
      id: RunicDayId.LuciaMesse,
    },
    {
      date: getDateString(21, 12, year),
      name: 'Tomasmesse I, Tomas brygger',
      type: 'runic',
      id: RunicDayId.ThomasMesse,
    },
    {
      date: getDateString(22, 12, year),
      name: 'Vintersolverv',
      type: 'runic',
      id: RunicDayId.WinterSolstice,
    },
    {
      date: getDateString(23, 12, year),
      name: 'Tollesmesse, Sjursmesse, lille julaften, vaskenatt',
      type: 'runic',
      id: RunicDayId.TolleMesse,
    },
    {
      date: getDateString(25, 12, year),
      name: 'Juledag, Natalis Christi',
      type: 'runic',
      id: RunicDayId.ChristmasDayRunic,
    },
    {
      date: getDateString(28, 12, year),
      name: 'Barnedag, barnemesse',
      type: 'runic',
      id: RunicDayId.ChildrensDay,
    },
  ]
}
